// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: jd_search_common.proto

package jd.search.common;

public final class JdSearchCommon {
  private JdSearchCommon() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code jd.search.common.JDStatisticType}
   */
  public enum JDStatisticType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>JD_DEFAULT_COL = 0;</code>
     */
    JD_DEFAULT_COL(0, 0),
    /**
     * <code>JD_COLOR_COL = 1;</code>
     */
    JD_COLOR_COL(1, 1),
    /**
     * <code>JD_EXTATTR_COL = 2;</code>
     */
    JD_EXTATTR_COL(2, 2),
    /**
     * <code>JD_SIZE_COL = 3;</code>
     */
    JD_SIZE_COL(3, 3),
    /**
     * <code>JD_SHOE_SIZE_COL = 4;</code>
     */
    JD_SHOE_SIZE_COL(4, 4),
    /**
     * <code>JD_DISCOUNT_COL = 5;</code>
     */
    JD_DISCOUNT_COL(5, 5),
    /**
     * <code>JD_SHOP_COL = 6;</code>
     */
    JD_SHOP_COL(6, 6),
    /**
     * <code>JD_STAR_LEVEL_COL = 7;</code>
     */
    JD_STAR_LEVEL_COL(7, 7),
    /**
     * <code>JD_PUBLISHER_COL = 8;</code>
     */
    JD_PUBLISHER_COL(8, 8),
    /**
     * <code>JD_CATEGORY_COL = 9;</code>
     */
    JD_CATEGORY_COL(9, 9),
    /**
     * <code>JD_BRAND_COL = 10;</code>
     */
    JD_BRAND_COL(10, 10),
    /**
     * <code>JD_PRICE_COL = 11;</code>
     */
    JD_PRICE_COL(11, 11),
    /**
     * <code>JD_PACKSTATE_COL = 12;</code>
     *
     * <pre>
     * 图书是否套装（套装，单品）
     * </pre>
     */
    JD_PACKSTATE_COL(12, 12),
    /**
     * <code>JD_PACKAGE_COL = 13;</code>
     *
     * <pre>
     * 装帧&amp;包装
     * </pre>
     */
    JD_PACKAGE_COL(13, 13),
    /**
     * <code>JD_MEDIA_COL = 14;</code>
     *
     * <pre>
     * 音像介质
     * </pre>
     */
    JD_MEDIA_COL(14, 14),
    /**
     * <code>JD_DREGION_COL = 15;</code>
     *
     * <pre>
     * 音像地区
     * </pre>
     */
    JD_DREGION_COL(15, 15),
    /**
     * <code>JD_PROMOTION_COL = 16;</code>
     *
     * <pre>
     * 活动
     * </pre>
     */
    JD_PROMOTION_COL(16, 16),
    /**
     * <code>JD_VIRTUAL_CATEGORYS_COL = 17;</code>
     *
     * <pre>
     *虚拟类目汇总
     * </pre>
     */
    JD_VIRTUAL_CATEGORYS_COL(17, 17),
    /**
     * <code>JD_EXIST_STATISTIC_COL = 18;</code>
     *
     * <pre>
     * 统计满足某过滤字段商品结果数
     * </pre>
     */
    JD_EXIST_STATISTIC_COL(18, 18),
    ;

    /**
     * <code>JD_DEFAULT_COL = 0;</code>
     */
    public static final int JD_DEFAULT_COL_VALUE = 0;
    /**
     * <code>JD_COLOR_COL = 1;</code>
     */
    public static final int JD_COLOR_COL_VALUE = 1;
    /**
     * <code>JD_EXTATTR_COL = 2;</code>
     */
    public static final int JD_EXTATTR_COL_VALUE = 2;
    /**
     * <code>JD_SIZE_COL = 3;</code>
     */
    public static final int JD_SIZE_COL_VALUE = 3;
    /**
     * <code>JD_SHOE_SIZE_COL = 4;</code>
     */
    public static final int JD_SHOE_SIZE_COL_VALUE = 4;
    /**
     * <code>JD_DISCOUNT_COL = 5;</code>
     */
    public static final int JD_DISCOUNT_COL_VALUE = 5;
    /**
     * <code>JD_SHOP_COL = 6;</code>
     */
    public static final int JD_SHOP_COL_VALUE = 6;
    /**
     * <code>JD_STAR_LEVEL_COL = 7;</code>
     */
    public static final int JD_STAR_LEVEL_COL_VALUE = 7;
    /**
     * <code>JD_PUBLISHER_COL = 8;</code>
     */
    public static final int JD_PUBLISHER_COL_VALUE = 8;
    /**
     * <code>JD_CATEGORY_COL = 9;</code>
     */
    public static final int JD_CATEGORY_COL_VALUE = 9;
    /**
     * <code>JD_BRAND_COL = 10;</code>
     */
    public static final int JD_BRAND_COL_VALUE = 10;
    /**
     * <code>JD_PRICE_COL = 11;</code>
     */
    public static final int JD_PRICE_COL_VALUE = 11;
    /**
     * <code>JD_PACKSTATE_COL = 12;</code>
     *
     * <pre>
     * 图书是否套装（套装，单品）
     * </pre>
     */
    public static final int JD_PACKSTATE_COL_VALUE = 12;
    /**
     * <code>JD_PACKAGE_COL = 13;</code>
     *
     * <pre>
     * 装帧&amp;包装
     * </pre>
     */
    public static final int JD_PACKAGE_COL_VALUE = 13;
    /**
     * <code>JD_MEDIA_COL = 14;</code>
     *
     * <pre>
     * 音像介质
     * </pre>
     */
    public static final int JD_MEDIA_COL_VALUE = 14;
    /**
     * <code>JD_DREGION_COL = 15;</code>
     *
     * <pre>
     * 音像地区
     * </pre>
     */
    public static final int JD_DREGION_COL_VALUE = 15;
    /**
     * <code>JD_PROMOTION_COL = 16;</code>
     *
     * <pre>
     * 活动
     * </pre>
     */
    public static final int JD_PROMOTION_COL_VALUE = 16;
    /**
     * <code>JD_VIRTUAL_CATEGORYS_COL = 17;</code>
     *
     * <pre>
     *虚拟类目汇总
     * </pre>
     */
    public static final int JD_VIRTUAL_CATEGORYS_COL_VALUE = 17;
    /**
     * <code>JD_EXIST_STATISTIC_COL = 18;</code>
     *
     * <pre>
     * 统计满足某过滤字段商品结果数
     * </pre>
     */
    public static final int JD_EXIST_STATISTIC_COL_VALUE = 18;


    public final int getNumber() { return value; }

    public static JDStatisticType valueOf(int value) {
      switch (value) {
        case 0: return JD_DEFAULT_COL;
        case 1: return JD_COLOR_COL;
        case 2: return JD_EXTATTR_COL;
        case 3: return JD_SIZE_COL;
        case 4: return JD_SHOE_SIZE_COL;
        case 5: return JD_DISCOUNT_COL;
        case 6: return JD_SHOP_COL;
        case 7: return JD_STAR_LEVEL_COL;
        case 8: return JD_PUBLISHER_COL;
        case 9: return JD_CATEGORY_COL;
        case 10: return JD_BRAND_COL;
        case 11: return JD_PRICE_COL;
        case 12: return JD_PACKSTATE_COL;
        case 13: return JD_PACKAGE_COL;
        case 14: return JD_MEDIA_COL;
        case 15: return JD_DREGION_COL;
        case 16: return JD_PROMOTION_COL;
        case 17: return JD_VIRTUAL_CATEGORYS_COL;
        case 18: return JD_EXIST_STATISTIC_COL;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<JDStatisticType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<JDStatisticType>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<JDStatisticType>() {
            public JDStatisticType findValueByNumber(int number) {
              return JDStatisticType.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return jd.search.common.JdSearchCommon.getDescriptor().getEnumTypes().get(0);
    }

    private static final JDStatisticType[] VALUES = values();

    public static JDStatisticType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private JDStatisticType(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:jd.search.common.JDStatisticType)
  }

  /**
   * Protobuf enum {@code jd.search.common.JDRetrieveType}
   */
  public enum JDRetrieveType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>JD_INTERSECTION = 0;</code>
     */
    JD_INTERSECTION(0, 0),
    /**
     * <code>JD_UNION = 1;</code>
     */
    JD_UNION(1, 1),
    /**
     * <code>JD_DIFFERENCE = 2;</code>
     */
    JD_DIFFERENCE(2, 2),
    ;

    /**
     * <code>JD_INTERSECTION = 0;</code>
     */
    public static final int JD_INTERSECTION_VALUE = 0;
    /**
     * <code>JD_UNION = 1;</code>
     */
    public static final int JD_UNION_VALUE = 1;
    /**
     * <code>JD_DIFFERENCE = 2;</code>
     */
    public static final int JD_DIFFERENCE_VALUE = 2;


    public final int getNumber() { return value; }

    public static JDRetrieveType valueOf(int value) {
      switch (value) {
        case 0: return JD_INTERSECTION;
        case 1: return JD_UNION;
        case 2: return JD_DIFFERENCE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<JDRetrieveType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<JDRetrieveType>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<JDRetrieveType>() {
            public JDRetrieveType findValueByNumber(int number) {
              return JDRetrieveType.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return jd.search.common.JdSearchCommon.getDescriptor().getEnumTypes().get(1);
    }

    private static final JDRetrieveType[] VALUES = values();

    public static JDRetrieveType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private JDRetrieveType(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:jd.search.common.JDRetrieveType)
  }

  /**
   * Protobuf enum {@code jd.search.common.ShopFiltType}
   */
  public enum ShopFiltType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>FILT_NONE = 0;</code>
     */
    FILT_NONE(0, 0),
    /**
     * <code>FILT_SELF_SUPPORT = 1;</code>
     */
    FILT_SELF_SUPPORT(1, 1),
    ;

    /**
     * <code>FILT_NONE = 0;</code>
     */
    public static final int FILT_NONE_VALUE = 0;
    /**
     * <code>FILT_SELF_SUPPORT = 1;</code>
     */
    public static final int FILT_SELF_SUPPORT_VALUE = 1;


    public final int getNumber() { return value; }

    public static ShopFiltType valueOf(int value) {
      switch (value) {
        case 0: return FILT_NONE;
        case 1: return FILT_SELF_SUPPORT;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ShopFiltType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<ShopFiltType>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ShopFiltType>() {
            public ShopFiltType findValueByNumber(int number) {
              return ShopFiltType.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return jd.search.common.JdSearchCommon.getDescriptor().getEnumTypes().get(2);
    }

    private static final ShopFiltType[] VALUES = values();

    public static ShopFiltType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private ShopFiltType(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:jd.search.common.ShopFiltType)
  }

  /**
   * Protobuf enum {@code jd.search.common.JdResultStatus}
   *
   * <pre>
   **
   * 信息状态
   * </pre>
   */
  public enum JdResultStatus
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>JD_RS_OK = 0;</code>
     *
     * <pre>
     * OK
     * </pre>
     */
    JD_RS_OK(0, 0),
    /**
     * <code>JD_RS_EUNKNOWN = 1;</code>
     *
     * <pre>
     * Unknown Error
     * </pre>
     */
    JD_RS_EUNKNOWN(1, 1),
    /**
     * <code>JD_RS_ETIMEOUT = 2;</code>
     *
     * <pre>
     * Timeout Error
     * </pre>
     */
    JD_RS_ETIMEOUT(2, 2),
    /**
     * <code>JD_RS_EINVALID_QUERY = 3;</code>
     *
     * <pre>
     * Invalid Query
     * </pre>
     */
    JD_RS_EINVALID_QUERY(3, 3),
    /**
     * <code>JD_RS_ESERVICE_BUSY = 4;</code>
     *
     * <pre>
     * Service Busy
     * </pre>
     */
    JD_RS_ESERVICE_BUSY(4, 4),
    /**
     * <code>JD_RS_MERGER_EXCEPTION = 5;</code>
     *
     * <pre>
     *Merger internal exception
     * </pre>
     */
    JD_RS_MERGER_EXCEPTION(5, 5),
    /**
     * <code>JD_RS_SEARCHER_EXCEPTION = 6;</code>
     *
     * <pre>
     *At least one searcher node exception
     * </pre>
     */
    JD_RS_SEARCHER_EXCEPTION(6, 6),
    /**
     * <code>JD_RS_DETAIL_EXCEPTION = 7;</code>
     *
     * <pre>
     *one detail node exception
     * </pre>
     */
    JD_RS_DETAIL_EXCEPTION(7, 7),
    /**
     * <code>JD_RS_SEARCHER_DOWN = 8;</code>
     *
     * <pre>
     * At least one searcher down  in this request
     * </pre>
     */
    JD_RS_SEARCHER_DOWN(8, 8),
    /**
     * <code>JD_RS_SEARCHER_DOWN_COL = 9;</code>
     *
     * <pre>
     *At least one searcher column down
     * </pre>
     */
    JD_RS_SEARCHER_DOWN_COL(9, 9),
    /**
     * <code>JD_RS_SEARCHER_TIMEOUT = 10;</code>
     *
     * <pre>
     *At least one searcher node timeout
     * </pre>
     */
    JD_RS_SEARCHER_TIMEOUT(10, 10),
    /**
     * <code>JD_RS_DETAIL_DOWN = 11;</code>
     *
     * <pre>
     * one detail down in this request
     * </pre>
     */
    JD_RS_DETAIL_DOWN(11, 11),
    /**
     * <code>JD_RS_DETAIL_DOWN_COL = 12;</code>
     *
     * <pre>
     *detail column down
     * </pre>
     */
    JD_RS_DETAIL_DOWN_COL(12, 12),
    /**
     * <code>JD_RS_DETAIL_TIMEOUT = 13;</code>
     *
     * <pre>
     *one detail node timeout
     * </pre>
     */
    JD_RS_DETAIL_TIMEOUT(13, 13),
    ;

    /**
     * <code>JD_RS_OK = 0;</code>
     *
     * <pre>
     * OK
     * </pre>
     */
    public static final int JD_RS_OK_VALUE = 0;
    /**
     * <code>JD_RS_EUNKNOWN = 1;</code>
     *
     * <pre>
     * Unknown Error
     * </pre>
     */
    public static final int JD_RS_EUNKNOWN_VALUE = 1;
    /**
     * <code>JD_RS_ETIMEOUT = 2;</code>
     *
     * <pre>
     * Timeout Error
     * </pre>
     */
    public static final int JD_RS_ETIMEOUT_VALUE = 2;
    /**
     * <code>JD_RS_EINVALID_QUERY = 3;</code>
     *
     * <pre>
     * Invalid Query
     * </pre>
     */
    public static final int JD_RS_EINVALID_QUERY_VALUE = 3;
    /**
     * <code>JD_RS_ESERVICE_BUSY = 4;</code>
     *
     * <pre>
     * Service Busy
     * </pre>
     */
    public static final int JD_RS_ESERVICE_BUSY_VALUE = 4;
    /**
     * <code>JD_RS_MERGER_EXCEPTION = 5;</code>
     *
     * <pre>
     *Merger internal exception
     * </pre>
     */
    public static final int JD_RS_MERGER_EXCEPTION_VALUE = 5;
    /**
     * <code>JD_RS_SEARCHER_EXCEPTION = 6;</code>
     *
     * <pre>
     *At least one searcher node exception
     * </pre>
     */
    public static final int JD_RS_SEARCHER_EXCEPTION_VALUE = 6;
    /**
     * <code>JD_RS_DETAIL_EXCEPTION = 7;</code>
     *
     * <pre>
     *one detail node exception
     * </pre>
     */
    public static final int JD_RS_DETAIL_EXCEPTION_VALUE = 7;
    /**
     * <code>JD_RS_SEARCHER_DOWN = 8;</code>
     *
     * <pre>
     * At least one searcher down  in this request
     * </pre>
     */
    public static final int JD_RS_SEARCHER_DOWN_VALUE = 8;
    /**
     * <code>JD_RS_SEARCHER_DOWN_COL = 9;</code>
     *
     * <pre>
     *At least one searcher column down
     * </pre>
     */
    public static final int JD_RS_SEARCHER_DOWN_COL_VALUE = 9;
    /**
     * <code>JD_RS_SEARCHER_TIMEOUT = 10;</code>
     *
     * <pre>
     *At least one searcher node timeout
     * </pre>
     */
    public static final int JD_RS_SEARCHER_TIMEOUT_VALUE = 10;
    /**
     * <code>JD_RS_DETAIL_DOWN = 11;</code>
     *
     * <pre>
     * one detail down in this request
     * </pre>
     */
    public static final int JD_RS_DETAIL_DOWN_VALUE = 11;
    /**
     * <code>JD_RS_DETAIL_DOWN_COL = 12;</code>
     *
     * <pre>
     *detail column down
     * </pre>
     */
    public static final int JD_RS_DETAIL_DOWN_COL_VALUE = 12;
    /**
     * <code>JD_RS_DETAIL_TIMEOUT = 13;</code>
     *
     * <pre>
     *one detail node timeout
     * </pre>
     */
    public static final int JD_RS_DETAIL_TIMEOUT_VALUE = 13;


    public final int getNumber() { return value; }

    public static JdResultStatus valueOf(int value) {
      switch (value) {
        case 0: return JD_RS_OK;
        case 1: return JD_RS_EUNKNOWN;
        case 2: return JD_RS_ETIMEOUT;
        case 3: return JD_RS_EINVALID_QUERY;
        case 4: return JD_RS_ESERVICE_BUSY;
        case 5: return JD_RS_MERGER_EXCEPTION;
        case 6: return JD_RS_SEARCHER_EXCEPTION;
        case 7: return JD_RS_DETAIL_EXCEPTION;
        case 8: return JD_RS_SEARCHER_DOWN;
        case 9: return JD_RS_SEARCHER_DOWN_COL;
        case 10: return JD_RS_SEARCHER_TIMEOUT;
        case 11: return JD_RS_DETAIL_DOWN;
        case 12: return JD_RS_DETAIL_DOWN_COL;
        case 13: return JD_RS_DETAIL_TIMEOUT;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<JdResultStatus>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<JdResultStatus>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<JdResultStatus>() {
            public JdResultStatus findValueByNumber(int number) {
              return JdResultStatus.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return jd.search.common.JdSearchCommon.getDescriptor().getEnumTypes().get(3);
    }

    private static final JdResultStatus[] VALUES = values();

    public static JdResultStatus valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private JdResultStatus(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:jd.search.common.JdResultStatus)
  }

  /**
   * Protobuf enum {@code jd.search.common.SourceType}
   *
   * <pre>
   **
   * 用户个性化行为来源
   * </pre>
   */
  public enum SourceType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>PC = 0;</code>
     *
     * <pre>
     *PC
     * </pre>
     */
    PC(0, 0),
    /**
     * <code>APP = 1;</code>
     *
     * <pre>
     *APP
     * </pre>
     */
    APP(1, 1),
    /**
     * <code>WX = 2;</code>
     *
     * <pre>
     *WeiXin
     * </pre>
     */
    WX(2, 2),
    /**
     * <code>ShouQ = 3;</code>
     *
     * <pre>
     *手机QQ
     * </pre>
     */
    ShouQ(3, 3),
    /**
     * <code>ALL = 4;</code>
     *
     * <pre>
     *全部渠道
     * </pre>
     */
    ALL(4, 4),
    /**
     * <code>OTHER = 5;</code>
     *
     * <pre>
     *其他渠道
     * </pre>
     */
    OTHER(5, 5),
    ;

    /**
     * <code>PC = 0;</code>
     *
     * <pre>
     *PC
     * </pre>
     */
    public static final int PC_VALUE = 0;
    /**
     * <code>APP = 1;</code>
     *
     * <pre>
     *APP
     * </pre>
     */
    public static final int APP_VALUE = 1;
    /**
     * <code>WX = 2;</code>
     *
     * <pre>
     *WeiXin
     * </pre>
     */
    public static final int WX_VALUE = 2;
    /**
     * <code>ShouQ = 3;</code>
     *
     * <pre>
     *手机QQ
     * </pre>
     */
    public static final int ShouQ_VALUE = 3;
    /**
     * <code>ALL = 4;</code>
     *
     * <pre>
     *全部渠道
     * </pre>
     */
    public static final int ALL_VALUE = 4;
    /**
     * <code>OTHER = 5;</code>
     *
     * <pre>
     *其他渠道
     * </pre>
     */
    public static final int OTHER_VALUE = 5;


    public final int getNumber() { return value; }

    public static SourceType valueOf(int value) {
      switch (value) {
        case 0: return PC;
        case 1: return APP;
        case 2: return WX;
        case 3: return ShouQ;
        case 4: return ALL;
        case 5: return OTHER;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<SourceType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<SourceType>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<SourceType>() {
            public SourceType findValueByNumber(int number) {
              return SourceType.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return jd.search.common.JdSearchCommon.getDescriptor().getEnumTypes().get(4);
    }

    private static final SourceType[] VALUES = values();

    public static SourceType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private SourceType(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:jd.search.common.SourceType)
  }

  public interface JdStringPairOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required bytes key = 1;
    /**
     * <code>required bytes key = 1;</code>
     */
    boolean hasKey();
    /**
     * <code>required bytes key = 1;</code>
     */
    com.google.protobuf.ByteString getKey();

    // required bytes value = 2;
    /**
     * <code>required bytes value = 2;</code>
     */
    boolean hasValue();
    /**
     * <code>required bytes value = 2;</code>
     */
    com.google.protobuf.ByteString getValue();
  }
  /**
   * Protobuf type {@code jd.search.common.JdStringPair}
   */
  public static final class JdStringPair extends
      com.google.protobuf.GeneratedMessage
      implements JdStringPairOrBuilder {
    // Use JdStringPair.newBuilder() to construct.
    private JdStringPair(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private JdStringPair(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final JdStringPair defaultInstance;
    public static JdStringPair getDefaultInstance() {
      return defaultInstance;
    }

    public JdStringPair getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private JdStringPair(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              key_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              value_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return jd.search.common.JdSearchCommon.internal_static_jd_search_common_JdStringPair_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return jd.search.common.JdSearchCommon.internal_static_jd_search_common_JdStringPair_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              jd.search.common.JdSearchCommon.JdStringPair.class, jd.search.common.JdSearchCommon.JdStringPair.Builder.class);
    }

    public static com.google.protobuf.Parser<JdStringPair> PARSER =
        new com.google.protobuf.AbstractParser<JdStringPair>() {
      public JdStringPair parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new JdStringPair(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<JdStringPair> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required bytes key = 1;
    public static final int KEY_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString key_;
    /**
     * <code>required bytes key = 1;</code>
     */
    public boolean hasKey() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required bytes key = 1;</code>
     */
    public com.google.protobuf.ByteString getKey() {
      return key_;
    }

    // required bytes value = 2;
    public static final int VALUE_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString value_;
    /**
     * <code>required bytes value = 2;</code>
     */
    public boolean hasValue() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required bytes value = 2;</code>
     */
    public com.google.protobuf.ByteString getValue() {
      return value_;
    }

    private void initFields() {
      key_ = com.google.protobuf.ByteString.EMPTY;
      value_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasKey()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasValue()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, key_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, value_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, key_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, value_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static jd.search.common.JdSearchCommon.JdStringPair parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static jd.search.common.JdSearchCommon.JdStringPair parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static jd.search.common.JdSearchCommon.JdStringPair parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static jd.search.common.JdSearchCommon.JdStringPair parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static jd.search.common.JdSearchCommon.JdStringPair parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static jd.search.common.JdSearchCommon.JdStringPair parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static jd.search.common.JdSearchCommon.JdStringPair parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static jd.search.common.JdSearchCommon.JdStringPair parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static jd.search.common.JdSearchCommon.JdStringPair parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static jd.search.common.JdSearchCommon.JdStringPair parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(jd.search.common.JdSearchCommon.JdStringPair prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code jd.search.common.JdStringPair}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements jd.search.common.JdSearchCommon.JdStringPairOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return jd.search.common.JdSearchCommon.internal_static_jd_search_common_JdStringPair_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return jd.search.common.JdSearchCommon.internal_static_jd_search_common_JdStringPair_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                jd.search.common.JdSearchCommon.JdStringPair.class, jd.search.common.JdSearchCommon.JdStringPair.Builder.class);
      }

      // Construct using jd.search.common.JdSearchCommon.JdStringPair.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        key_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        value_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return jd.search.common.JdSearchCommon.internal_static_jd_search_common_JdStringPair_descriptor;
      }

      public jd.search.common.JdSearchCommon.JdStringPair getDefaultInstanceForType() {
        return jd.search.common.JdSearchCommon.JdStringPair.getDefaultInstance();
      }

      public jd.search.common.JdSearchCommon.JdStringPair build() {
        jd.search.common.JdSearchCommon.JdStringPair result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public jd.search.common.JdSearchCommon.JdStringPair buildPartial() {
        jd.search.common.JdSearchCommon.JdStringPair result = new jd.search.common.JdSearchCommon.JdStringPair(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.key_ = key_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.value_ = value_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof jd.search.common.JdSearchCommon.JdStringPair) {
          return mergeFrom((jd.search.common.JdSearchCommon.JdStringPair)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(jd.search.common.JdSearchCommon.JdStringPair other) {
        if (other == jd.search.common.JdSearchCommon.JdStringPair.getDefaultInstance()) return this;
        if (other.hasKey()) {
          setKey(other.getKey());
        }
        if (other.hasValue()) {
          setValue(other.getValue());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasKey()) {
          
          return false;
        }
        if (!hasValue()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        jd.search.common.JdSearchCommon.JdStringPair parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (jd.search.common.JdSearchCommon.JdStringPair) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required bytes key = 1;
      private com.google.protobuf.ByteString key_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes key = 1;</code>
       */
      public boolean hasKey() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required bytes key = 1;</code>
       */
      public com.google.protobuf.ByteString getKey() {
        return key_;
      }
      /**
       * <code>required bytes key = 1;</code>
       */
      public Builder setKey(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        key_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes key = 1;</code>
       */
      public Builder clearKey() {
        bitField0_ = (bitField0_ & ~0x00000001);
        key_ = getDefaultInstance().getKey();
        onChanged();
        return this;
      }

      // required bytes value = 2;
      private com.google.protobuf.ByteString value_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes value = 2;</code>
       */
      public boolean hasValue() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required bytes value = 2;</code>
       */
      public com.google.protobuf.ByteString getValue() {
        return value_;
      }
      /**
       * <code>required bytes value = 2;</code>
       */
      public Builder setValue(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        value_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes value = 2;</code>
       */
      public Builder clearValue() {
        bitField0_ = (bitField0_ & ~0x00000002);
        value_ = getDefaultInstance().getValue();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:jd.search.common.JdStringPair)
    }

    static {
      defaultInstance = new JdStringPair(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:jd.search.common.JdStringPair)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_jd_search_common_JdStringPair_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_jd_search_common_JdStringPair_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026jd_search_common.proto\022\020jd.search.comm" +
      "on\"*\n\014JdStringPair\022\013\n\003key\030\001 \002(\014\022\r\n\005value" +
      "\030\002 \002(\014*\236\003\n\017JDStatisticType\022\022\n\016JD_DEFAULT" +
      "_COL\020\000\022\020\n\014JD_COLOR_COL\020\001\022\022\n\016JD_EXTATTR_C" +
      "OL\020\002\022\017\n\013JD_SIZE_COL\020\003\022\024\n\020JD_SHOE_SIZE_CO" +
      "L\020\004\022\023\n\017JD_DISCOUNT_COL\020\005\022\017\n\013JD_SHOP_COL\020" +
      "\006\022\025\n\021JD_STAR_LEVEL_COL\020\007\022\024\n\020JD_PUBLISHER" +
      "_COL\020\010\022\023\n\017JD_CATEGORY_COL\020\t\022\020\n\014JD_BRAND_" +
      "COL\020\n\022\020\n\014JD_PRICE_COL\020\013\022\024\n\020JD_PACKSTATE_" +
      "COL\020\014\022\022\n\016JD_PACKAGE_COL\020\r\022\020\n\014JD_MEDIA_CO",
      "L\020\016\022\022\n\016JD_DREGION_COL\020\017\022\024\n\020JD_PROMOTION_" +
      "COL\020\020\022\034\n\030JD_VIRTUAL_CATEGORYS_COL\020\021\022\032\n\026J" +
      "D_EXIST_STATISTIC_COL\020\022*F\n\016JDRetrieveTyp" +
      "e\022\023\n\017JD_INTERSECTION\020\000\022\014\n\010JD_UNION\020\001\022\021\n\r" +
      "JD_DIFFERENCE\020\002*4\n\014ShopFiltType\022\r\n\tFILT_" +
      "NONE\020\000\022\025\n\021FILT_SELF_SUPPORT\020\001*\355\002\n\016JdResu" +
      "ltStatus\022\014\n\010JD_RS_OK\020\000\022\022\n\016JD_RS_EUNKNOWN" +
      "\020\001\022\022\n\016JD_RS_ETIMEOUT\020\002\022\030\n\024JD_RS_EINVALID" +
      "_QUERY\020\003\022\027\n\023JD_RS_ESERVICE_BUSY\020\004\022\032\n\026JD_" +
      "RS_MERGER_EXCEPTION\020\005\022\034\n\030JD_RS_SEARCHER_",
      "EXCEPTION\020\006\022\032\n\026JD_RS_DETAIL_EXCEPTION\020\007\022" +
      "\027\n\023JD_RS_SEARCHER_DOWN\020\010\022\033\n\027JD_RS_SEARCH" +
      "ER_DOWN_COL\020\t\022\032\n\026JD_RS_SEARCHER_TIMEOUT\020" +
      "\n\022\025\n\021JD_RS_DETAIL_DOWN\020\013\022\031\n\025JD_RS_DETAIL" +
      "_DOWN_COL\020\014\022\030\n\024JD_RS_DETAIL_TIMEOUT\020\r*D\n" +
      "\nSourceType\022\006\n\002PC\020\000\022\007\n\003APP\020\001\022\006\n\002WX\020\002\022\t\n\005" +
      "ShouQ\020\003\022\007\n\003ALL\020\004\022\t\n\005OTHER\020\005"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_jd_search_common_JdStringPair_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_jd_search_common_JdStringPair_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_jd_search_common_JdStringPair_descriptor,
              new java.lang.String[] { "Key", "Value", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
